# Generated by Django 4.0.4 on 2022-10-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmodel',
            name='role',
            field=models.CharField(max_length=250, verbose_name='Role'),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
