# Generated by Django 4.0.4 on 2022-11-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('discription', models.TextField(verbose_name='discription')),
                ('author', models.CharField(max_length=100, verbose_name='author')),
                ('url', models.SlugField(max_length=100)),
            ],
        ),
    ]
