# Generated by Django 4.0.4 on 2022-11-24 13:51
from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension,TrigramExtension
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        UnaccentExtension(),
        TrigramExtension(),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='gello', max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='publicationmodel',
            name='url',
        ),
        migrations.AddField(
            model_name='publicationmodel',
            name='date_of_create',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicationmodel',
            name='date_of_update',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='publicationmodel',
            name='time_of_create',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicationmodel',
            name='time_of_update',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='publicationmodel',
            name='tags',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='news.tags'),
        ),
    ]
