# Generated by Django 4.1.4 on 2022-12-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_tags_remove_publicationmodel_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationmodel',
            name='title_image',
            field=models.ImageField(default='default.jpg', upload_to='news'),
        ),
    ]
