# Generated by Django 4.1.4 on 2022-12-27 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_publicationmodel_title_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Processing', max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Article', max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='publicationmodel',
            name='status',
            field=models.ForeignKey(null=True,on_delete=django.db.models.deletion.CASCADE, to='news.status'),
        ),
        migrations.AddField(
            model_name='publicationmodel',
            name='type',
            field=models.ForeignKey(null=True,on_delete=django.db.models.deletion.CASCADE, to='news.typeofrequest'),
        ),
    ]
