# Generated by Django 4.1.4 on 2022-12-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_status_typeofrequest_publicationmodel_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationmodel',
            name='review',
            field=models.TextField(blank=True, null=True, verbose_name='Review'),
        ),
    ]
