# Generated by Django 4.1.4 on 2022-12-28 15:18

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension
class Migration(migrations.Migration):
    dependencies = [
        ('news', '0005_publicationmodel_review'),
    ]
    operations = [
        TrigramExtension(),
        UnaccentExtension()
    ]
