# Generated by Django 4.1.4 on 2023-01-02 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_remove_registrationmodel_is_active_and_more'),
        ('news', '0006_auto_20221228_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationmodel',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.registrationmodel'),
        ),
    ]
