# Generated by Django 4.1.4 on 2023-01-05 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_remove_registrationmodel_is_active_and_more'),
        ('news', '0007_alter_publicationmodel_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=150, verbose_name='Room Name')),
                ('message', models.TextField(verbose_name='Message')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.registrationmodel')),
            ],
        ),
    ]
