# Generated by Django 4.1.4 on 2023-01-05 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_remove_registrationmodel_is_active_and_more'),
        ('news', '0008_chatmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=250, verbose_name='Last_Name')),
                ('name', models.CharField(max_length=250, verbose_name='First_Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('friend', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.registrationmodel')),
            ],
        ),
    ]
