# Generated by Django 4.1.4 on 2023-01-05 22:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_friendmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='date_of_create',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='date_of_update',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='time_of_create',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='time_of_update',
            field=models.TimeField(auto_now=True),
        ),
    ]
