# Generated by Django 4.1.5 on 2023-01-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_chatmodel_date_of_create_chatmodel_date_of_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='chanel_name',
            field=models.CharField(max_length=150, null=True, verbose_name='chanel Name'),
        ),
    ]
