# Generated by Django 4.1.5 on 2023-01-08 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_chatmodel_getter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmodel',
            name='chanel_name',
        ),
    ]
