# Generated by Django 4.1.5 on 2023-01-08 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_remove_registrationmodel_is_active_and_more'),
        ('news', '0013_remove_chatmodel_chanel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmodel',
            name='getter',
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='register.registrationmodel'),
        ),
    ]
