# Generated by Django 4.1.5 on 2023-01-08 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_remove_registrationmodel_is_active_and_more'),
        ('news', '0014_remove_chatmodel_getter_chatmodel_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatModel',
            new_name='MessageModel',
        ),
    ]
