# Generated by Django 4.1.5 on 2023-01-08 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_remove_registrationmodel_is_active_and_more'),
        ('news', '0015_rename_chatmodel_messagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=150, verbose_name='Room Name')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holder', to='register.registrationmodel')),
            ],
        ),
    ]
