# Generated by Django 4.1.5 on 2023-01-08 17:00

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension

class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_chatmodel_guest'),
    ]

    operations = [

        TrigramExtension(),
        UnaccentExtension(),
    ]
