# Generated by Django 4.1.5 on 2023-01-08 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_auto_20230108_1900'),
    ]

    operations = [
        migrations.RunSQL('CREATE EXTENSION IF NOT EXISTS pg_trgm'),
    ]
