# Generated by Django 4.1.5 on 2023-01-09 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_remove_registrationmodel_is_active_and_more'),
        ('news', '0019_auto_20230108_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmodel',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='chatmodel',
            name='holder',
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='register.registrationmodel'),
        ),
    ]
