# Generated by Django 4.1.5 on 2023-01-09 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_remove_chatmodel_guest_remove_chatmodel_holder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagemodel',
            name='sender',
        ),
    ]
