# Generated by Django 4.1.5 on 2023-01-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_chatmodel_channel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Processing', max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active Chat'),
        ),
    ]
