# Generated by Django 4.1.5 on 2023-01-12 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_remove_registrationmodel_is_active_and_more'),
        ('news', '0024_statuschat_chatmodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='friendmodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='getter', to='register.registrationmodel'),
        ),
    ]
