# Generated by Django 4.1.5 on 2023-01-12 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_chatmodel_type_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullStateOfChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='full_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.fullstateofchat'),
        ),
    ]
