# Generated by Django 4.1.5 on 2023-01-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0027_fullstateofchat_chatmodel_full_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='name',
            field=models.CharField(max_length=250, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='surname',
            field=models.CharField(max_length=250, null=True, verbose_name='Last Name'),
        ),
    ]
