# Generated by Django 4.0.4 on 2022-10-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_registrationmodel_role_delete_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmodel',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email'),
        ),
    ]
