# Generated by Django 4.0.4 on 2022-10-29 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0002_remove_buildmodel_build_remove_roommodel_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=250, verbose_name='Last_Name')),
                ('first_name', models.CharField(max_length=250, verbose_name='First_Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('password', models.CharField(max_length=250, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, verbose_name='About')),
            ],
        ),
        migrations.DeleteModel(
            name='BuildModel',
        ),
        migrations.DeleteModel(
            name='RoomModel',
        ),
        migrations.AddField(
            model_name='registrationmodel',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nav.role'),
        ),
    ]
