# Generated by Django 4.0.4 on 2022-10-29 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0003_registrationmodel_role_delete_buildmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=22)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nav.campus')),
            ],
        ),
        migrations.DeleteModel(
            name='RegistrationModel',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
